_BASE_: "Base-RCNN-DilatedC5.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN_WSOVOD"
  BACKBONE:
    NAME: "RFDETRBackbone"
    FREEZE_AT: 0
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]
  LOAD_PROPOSALS: True
  PROPOSAL_GENERATOR:
    NAME: "RFDETRProposalGenerator"
    MIN_SIZE: 40
  RFDETR:
    # 模型配置
    ENCODER: "dinov2_windowed_small"
    HIDDEN_DIM: 256
    SA_NHEADS: 8
    CA_NHEADS: 16
    NUM_QUERIES: 300
    DEC_LAYERS: 3
    OUT_FEATURE_NAMES: ["p3", "p4", "p5", "p6"]
    IN_FEATURES: ["p3", "p4", "p5", "p6"]
    PROJECTOR_SCALE: ["P3", "P4", "P5", "P6"]
    OUT_FEATURE_INDEXES: [2, 5, 8, 11]
    NUM_CLASSES: 80  # COCO有80个类别
    # 训练配置
    FREEZE_ENCODER: True  # 保持主干网络冻结
    RESOLUTION: 640
    DEC_N_POINTS: 4
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    LITE_REFPOINT_REFINE: True
    GROUP_DETR: 1
    TWO_STAGE: True
    DECODER_NORM: "LN"
    BOX_REPARAM: True
  RPN:
    IN_FEATURES: ["p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2048
    PRE_NMS_TOPK_TEST: 2048
    POST_NMS_TOPK_TRAIN: 1024
    POST_NMS_TOPK_TEST: 1024
    NMS_THRESH: 0.7
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.5
  ROI_HEADS:
    IN_FEATURES: ["p3", "p4", "p5", "p6"]
    BATCH_SIZE_PER_IMAGE: 4096
    POSITIVE_FRACTION: 1.0
    PROPOSAL_APPEND_GT: True
  ROI_BOX_HEAD:
    OPEN_VOCABULARY:
      WEIGHT_PATH_TRAIN: "models/coco_text_embedding_single_prompt.pkl"
      WEIGHT_PATH_TEST: "models/coco_text_embedding_single_prompt.pkl"
WSOVOD:
  ITER_SIZE: 1
  BBOX_REFINE:
    ENABLE: True
  OBJECT_MINING:
    MEAN_LOSS: True
  INSTANCE_REFINEMENT:
    REFINE_NUM: 1
    REFINE_REG: [True]
  SAMPLING:
    SAMPLING_ON: True
    IOU_THRESHOLDS: [[0.5],]
    IOU_LABELS: [[0, 1],]
    BATCH_SIZE_PER_IMAGE: [4096,]
    POSITIVE_FRACTION: [1.0,]
SOLVER:
  STEPS: (140000,)  # COCO训练迭代次数通常更多
  MAX_ITER: 200000
  WARMUP_ITERS: 200
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001  # 较小的学习率
  WEIGHT_DECAY: 0.0005
  BIAS_LR_FACTOR: 2.0
  WEIGHT_DECAY_BIAS: 0.0
  OPTIMIZER: "ADAMW"  # 使用AdamW优化器
  BACKBONE_MULTIPLIER: 0.1  # 主干网络较小的学习率
INPUT:
  FORMAT: "RGB"  # 使用RGB格式，与DINOv2预训练一致
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  CROP:
    ENABLED: True
DATALOADER:
  NUM_WORKERS: 4
TEST:
  AUG:
    ENABLED: True
    MIN_SIZES: (480, 576, 672, 768, 864, 960, 1056, 1152)
    MAX_SIZE: 4000
    FLIP: True
  EVAL_PERIOD: 5000
  EVAL_TRAIN: False
DATASETS:
  TRAIN: ('coco_2017_train',)
  PROPOSAL_FILES_TRAIN: ('datasets/proposals/sam_coco_2017_train_d2.pkl',)
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 4000
  TEST: ('coco_2017_val',)
  PROPOSAL_FILES_TEST: ('datasets/proposals/sam_coco_2017_val_d2.pkl',)
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 4000
VIS_PERIOD: 10000
VERSION: 2